SQL Server db metadata reader

diff --git a/drivers/metadata/informationschema/Dockerfile b/drivers/metadata/informationschema/Dockerfile
--- a/drivers/metadata/informationschema/Dockerfile
+++ b/drivers/metadata/informationschema/Dockerfile
@@ -3,5 +3,6 @@ FROM $BASE_IMAGE
 
 ARG SCHEMA_URL
 ARG TARGET
-ADD $SCHEMA_URL $TARGET/
-RUN [ ! -d "$TARGET" ] || chmod -R 777 $TARGET/
+ARG USER
+ADD --chown=$USER $SCHEMA_URL $TARGET/
+RUN [ ! -d "$TARGET" ] || chmod -R 777 $TARGET/ || echo "failed to change perms of $TARGET, leaving as $(ls -la $TARGET/)"
